---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - openstack-tox-py27
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
