---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-nfv
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-py37
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-nfv
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-py37
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: nfv-tox-py27
    parent: tox
    description: Run py27 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: py27
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-py37
    parent: tox
    description: Run py37 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: py37
      tox_extra_args: -c nfv/tox.ini
      bindep_profile: test py37
      python_version: 3.7

- job:
    name: nfv-tox-pep8
    parent: tox
    description: Run pep8 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-pylint
    parent: tox
    description: Run pylint for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nova-api-proxy-tox-pep8
    parent: tox
    description: Run pep8 for nova-api-proxy
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: nova-api-proxy-tox-pylint
    parent: tox
    description: Run pylint for nova-api-proxy
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: flock-devstack-nfv
    parent: flock-devstack-base-min
    required-projects:
      - openstack/requirements
      - openstack/barbican
      - openstack/python-barbicanclient
      - openstack/stx-config
      - openstack/stx-fault
      - openstack/stx-integ
      - openstack/stx-metal
      - openstack/stx-update
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        cgtsclient: true
        fm-common: true
        fm-api: true
        fm-rest-api: true
        fm-mgr: true
        guest-client: true
        nfv-common: true
        nfv-vim: true
        nfv-client: true
      devstack_plugins:
        requirements: https://git.openstack.org/openstack/requirements
        barbican: https://git.openstack.org/openstack/barbican
        stx-fault: https:://git.starlingx.io/stx-fault
        stx-integ: https://git.starlingx.io/stx-integ
        stx-metal: https:://git.starlingx.io/stx-metal
        stx-nfv: https:://git.starlingx.io/stx-nfv
        stx-update: https:://git.starlingx.io/stx-update
        stx-config: git://git.starlingx.io/stx-config
