---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8
        - nfv-tox-unittest:
            voting: false
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-pep8

- job:
    name: nfv-tox-unittest
    parent: tox-py27
    description: |
      Run unit test for nfv
