---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint
    gate:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint

- job:
    name: nfv-tox-py27
    parent: tox
    description: Run py27 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: py27
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-pep8
    parent: tox
    description: Run pep8 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-pylint
    parent: tox
    description: Run pylint for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nova-api-proxy-tox-pep8
    parent: tox
    description: Run pep8 for nova-api-proxy
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: nova-api-proxy-tox-pylint
    parent: tox
    description: Run pylint for nova-api-proxy
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nova-api-proxy/tox.ini
