---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-py37
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint
        - stx-devstack-nfv:
            voting: false
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - nfv-tox-pep8
        - nfv-tox-py27
        - nfv-tox-py37
        - nfv-tox-pylint
        - nova-api-proxy-tox-pep8
        - nova-api-proxy-tox-pylint
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: nfv-tox-py27
    parent: tox
    description: Run py27 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: py27
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-py37
    parent: tox
    description: Run py37 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: py37
      tox_extra_args: -c nfv/tox.ini
      bindep_profile: test py37
      python_version: 3.7

- job:
    name: nfv-tox-pep8
    parent: tox
    description: Run pep8 for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nfv-tox-pylint
    parent: tox
    description: Run pylint for nfv
    required-projects:
      - openstack/stx-fault
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nfv/tox.ini

- job:
    name: nova-api-proxy-tox-pep8
    parent: tox
    description: Run pep8 for nova-api-proxy
    vars:
      tox_envlist: pep8
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: nova-api-proxy-tox-pylint
    parent: tox
    description: Run pylint for nova-api-proxy
    vars:
      tox_envlist: pylint
      tox_extra_args: -c nova-api-proxy/tox.ini

- job:
    name: stx-devstack-nfv
    parent: stx-devstack-base
    timeout: 7800
    required-projects:
      - openstack/stx-fault
      - openstack/stx-metal
      - openstack/stx-update
    vars:
      tox_envlist: functional
      devstack_services:
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false
        horizon: false
        # StarlingX services
        fm-common: true
        fm-api: true
        fm-rest-api: true
        fm-mgr: true
        nfv-common: true
        nfv-vim: true
        nfv-client: true
        guest-client: true
      devstack_plugins:
        stx-fault: git://git.starlingx.io/stx-fault
        stx-metal: git://git.starlingx.io/stx-metal
        stx-nfv: git://git.starlingx.io/stx-nfv
        stx-update: git://git.starlingx.io/stx-update
      devstack_localrc:
        LIBS_FROM_GIT: keystone
