#!/bin/bash
#
# lib/stx-nfv
# Functions to control the configuration and operation of stx-nfv

_XTRACE_STX_NFV=$(set +o | grep xtrace)
set -o xtrace

STXNFV_DIR=$DEST/stx-nfv
STXNFV_SYSCONFDIR=/etc

STX_BIN_DIR=$(get_python_exec_prefix)
STX_PREFIX=${STX_BIN_DIR%/*}

GUEST_CLIENT_VERSION="3.0.1"

STX_SDK_DEPLOY_DIR=${STX_SDK_DEPLOY_DIR:-/opt/deploy/cgcs_sdk}

function clean_guest_client {
    sudo rm -rf $STX_PREFIX/include/guest-client
    sudo rm -rf $STX_SDK_DEPLOY_DIR
    sudo rm -rf $STXNFV_SYSCONFDIR/systemd/system/guest-client.service
    sudo rm -rf $STXNFV_SYSCONFDIR/guest-client
    sudo rm -rf /usr/local/bin/guest-client
    sudo rm -rf /usr/local/lib/libguest_common_api.so.$GUEST_CLIENT_VERSION
    sudo rm -rf /usr/local/lib/libguest_heartbeat_api.so.$GUEST_CLIENT_VERSION
}

function install_guest_client {
    pushd $STXNFV_DIR/guest-client/guest-client-$GUEST_CLIENT_VERSION

    make clean
    make build sysconfdir=$STXNFV_SYSCONFDIR
    make sample
    make tar ARCHIVE_NAME=wrs-guest-heartbeat-$GUEST_CLIENT_VERSION
    find build

    # Sudo Install for guest-client package

    sudo install -m 755 -d $STX_PREFIX/include/guest-client
    sudo install -m 644 -p -D guest_client/src/heartbeat/guest_heartbeat_msg_defs.h $STX_PREFIX/include/guest-client/guest_heartbeat_msg_defs.h
    sudo install -d $STX_SDK_DEPLOY_DIR
    sudo install -m 640 build/wrs-guest-heartbeat-$GUEST_CLIENT_VERSION.tgz $STX_SDK_DEPLOY_DIR

    # Systemd services
    sudo install -m 644 -p -D guest_client/scripts/guest-client.service $STXNFV_SYSCONFDIR/systemd/system/guest-client.service
    sudo install -m 744 -p -D guest_client/scripts/guest-client.systemd $STXNFV_SYSCONFDIR/guest-client/guest-client.systemd

    sudo install -m 750 -d $STXNFV_SYSCONFDIR/guest-client/heartbeat
    sudo install -m 755 -p -D guest_client/scripts/guest_heartbeat.conf $STXNFV_SYSCONFDIR/guest-client/heartbeat/guest_heartbeat.conf
    sudo install -m 755 -p -D guest_client/scripts/sample_event_handling_script $STXNFV_SYSCONFDIR/guest-client/heartbeat/sample_event_handling_script
    sudo install -m 755 -p -D guest_client/scripts/sample_health_check_script $STXNFV_SYSCONFDIR/guest-client/heartbeat/sample_health_check_script
    sudo install -m 640 -p -D build/guest-client /usr/local/bin/guest-client
    sudo install -m 640 -p -D build/libguest_common_api.so.$GUEST_CLIENT_VERSION /usr/local/lib/libguest_common_api.so.$GUEST_CLIENT_VERSION
    sudo install -m 640 -p -D build/libguest_heartbeat_api.so.$GUEST_CLIENT_VERSION /usr/local/lib/libguest_heartbeat_api.so.$GUEST_CLIENT_VERSION

    popd
}

function install_nfv {
    if is_service_enabled guest-client; then
        install_guest_client
    fi
}

$_XTRACE_STX_NFV
