#!/bin/bash
# Devstack settings

# Defaults
# --------

STX_NFV_NAME=stx-nfv

######### Plugin Specific ##########
enable_service $STX_NFV_NAME nfv

# nfv services
if is_service_enabled nfv; then
    enable_service nfv-vim nfv-vim-api nfv-vim-webserver
fi

# Initial source of lib script
source $DEST/stx-nfv/devstack/lib/stx-nfv
