#
# Copyright (c) 2015-2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# flake8: noqa
#
from _rpc_defs import RPC_MSG_VERSION, RPC_MSG_TYPE, RPC_MSG_RESULT
from _rpc_message import RPCMessage

from _rpc_message_image import APIRequestCreateImage, APIResponseCreateImage
from _rpc_message_image import APIRequestUpdateImage, APIResponseUpdateImage
from _rpc_message_image import APIRequestDeleteImage, APIResponseDeleteImage
from _rpc_message_image import APIRequestGetImage, APIResponseGetImage

from _rpc_message_volume import APIRequestCreateVolume, APIResponseCreateVolume
from _rpc_message_volume import APIRequestUpdateVolume, APIResponseUpdateVolume
from _rpc_message_volume import APIRequestDeleteVolume, APIResponseDeleteVolume
from _rpc_message_volume import APIRequestGetVolume, APIResponseGetVolume

from _rpc_message_instance import APIRequestCreateInstance
from _rpc_message_instance import APIResponseCreateInstance
from _rpc_message_instance import APIRequestStartInstance
from _rpc_message_instance import APIResponseStartInstance
from _rpc_message_instance import APIRequestStopInstance
from _rpc_message_instance import APIResponseStopInstance
from _rpc_message_instance import APIRequestPauseInstance
from _rpc_message_instance import APIResponsePauseInstance
from _rpc_message_instance import APIRequestUnpauseInstance
from _rpc_message_instance import APIResponseUnpauseInstance
from _rpc_message_instance import APIRequestSuspendInstance
from _rpc_message_instance import APIResponseSuspendInstance
from _rpc_message_instance import APIRequestResumeInstance
from _rpc_message_instance import APIResponseResumeInstance
from _rpc_message_instance import APIRequestRebootInstance
from _rpc_message_instance import APIResponseRebootInstance
from _rpc_message_instance import APIRequestLiveMigrateInstance
from _rpc_message_instance import APIResponseLiveMigrateInstance
from _rpc_message_instance import APIRequestColdMigrateInstance
from _rpc_message_instance import APIResponseColdMigrateInstance
from _rpc_message_instance import APIRequestEvacuateInstance
from _rpc_message_instance import APIResponseEvacuateInstance
from _rpc_message_instance import APIRequestDeleteInstance
from _rpc_message_instance import APIResponseDeleteInstance
from _rpc_message_instance import APIRequestGetInstance
from _rpc_message_instance import APIResponseGetInstance

from _rpc_message_subnet import APIRequestCreateSubnet
from _rpc_message_subnet import APIResponseCreateSubnet
from _rpc_message_subnet import APIRequestUpdateSubnet
from _rpc_message_subnet import APIResponseUpdateSubnet
from _rpc_message_subnet import APIRequestDeleteSubnet
from _rpc_message_subnet import APIResponseDeleteSubnet
from _rpc_message_subnet import APIRequestGetSubnet, APIResponseGetSubnet

from _rpc_message_network import APIRequestCreateNetwork
from _rpc_message_network import APIResponseCreateNetwork
from _rpc_message_network import APIRequestUpdateNetwork
from _rpc_message_network import APIResponseUpdateNetwork
from _rpc_message_network import APIRequestDeleteNetwork
from _rpc_message_network import APIResponseDeleteNetwork
from _rpc_message_network import APIRequestGetNetwork, APIResponseGetNetwork

from _rpc_message_sw_update import APIRequestCreateSwUpdateStrategy
from _rpc_message_sw_update import APIRequestCreateSwUpgradeStrategy
from _rpc_message_sw_update import APIResponseCreateSwUpdateStrategy
from _rpc_message_sw_update import APIRequestApplySwUpdateStrategy
from _rpc_message_sw_update import APIResponseApplySwUpdateStrategy
from _rpc_message_sw_update import APIRequestAbortSwUpdateStrategy
from _rpc_message_sw_update import APIResponseAbortSwUpdateStrategy
from _rpc_message_sw_update import APIRequestDeleteSwUpdateStrategy
from _rpc_message_sw_update import APIResponseDeleteSwUpdateStrategy
from _rpc_message_sw_update import APIRequestGetSwUpdateStrategy
from _rpc_message_sw_update import APIResponseGetSwUpdateStrategy
